# for details see https://pre-commit.com
# for list of available hooks see https://pre-commmit/hooks.html
#
# Preclude commits that do not conform to various criteria

fail_fast: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.30
    hooks: #check for large files and aws credentials
      - id: check-added-large-files
        args: ["--maxkb=200"]
      - id: detect-aws-credentials
        args: ["--allow-missing-credentials"] # allow hook to pass when no credentials are detected
      - id: detect-private-key
  - repo: https://github.com/psf/black
    rev: 22.8.0
    hooks: # check conformance to black formatting
      - id: black
        args: ["--check"] # if run wihtout args, it will fail and it will format the files
  - repo: https://github.com/pycqa/flake8
    rev: 5.0.4
    hooks: #check conformance to PEP8, flake8 formatting
      - id: flake8
