name: Pylint

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        python-version: ["3.9","3.10"]
        os: [windows-latest, macos-latest, ubuntu-latest]
        
        
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install pylint
        pip install black
        pip install -r requirements-dev.txt
    - name: Lint with black
      run: |
        python -m black --check --diff .
    - name: Lint with flake8
      run: |
        python -m flake8 . --show-source --statistics
